# Numpy Assignment

1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.


In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 7, 13, 105])
print(arr1)
print(f"Type = {type(arr1)}")
print(f"Size = {arr1.size}")

[  1   7  13 105]
Type = <class 'numpy.ndarray'>
Size = 4


2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [4]:
def compare(arr1, arr2, i):
    # arr1 = np.array([11, 22, 33, 44, 55])
    # arr2 = np.array([50, 40, 33, 22, 11])

    if(arr1[i] == arr2[i]):
        print(f"Element at index {i} of arr1 = {arr1[i]} and arr2 = {arr2[i]} are equal")
    elif(arr1[i] > arr2[i]):
        print(f"Element at index {i} of arr1 = {arr1[i]} is greater than arr2 = {arr2[i]}")
    else:
        print(f"Element at index {i} of arr1 = {arr1[i]} is less than arr2 = {arr2[i]}")

    # for i in (0, arr1.size):
    #     if(arr1[i] == arr2[i]):
    #         print(f"Element at index {i} of arr1 = {arr1[i]} and arr2 = {arr2[i]} are equal")
    #     elif(arr1[i] > arr2[i]):
    #         print(f"Element at index {i} of arr1 = {arr1[i]} is greater than arr2 = {arr2[i]}")
    #     else:
    #        print(f"Element at index {i} of arr1 = {arr1[i]} is less than arr2 = {arr2[i]}")

        i = i + 1

arr1 = np.array([10, 20, 33, 40, 50])
arr2 = np.array([55, 44, 33, 22, 11])

compare(arr1, arr2, 3)


Element at index 3 of arr1 = 40 is greater than arr2 = 22


3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [5]:
arr = np.zeros(10)
print(arr)
arr = np.ones(10)
print(arr)
arr = arr * 5
print(arr)
arr = arr * 2
print(arr)
arr = arr * 2
print(arr)
arr = arr * 5/2
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


4. Write a NumPy program to create an array of integers from 30 to 70.

In [6]:
arr = np.arange(30, 71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


5. Write a NumPy program to create an array of integers from 50 to 95.

In [7]:
arr = np.arange(50, 96)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [8]:
arr = np.arange(20, 81, 2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [9]:
arr = np.arange(21, 80, 2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.


In [10]:
arr = np.random.randint(10, 40, 15)
print(arr)

[29 29 20 22 26 33 32 35 23 28 39 18 39 10 13]


9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [11]:
arr = np.random.randint(30, 50, 10)
print(arr)

[30 45 37 34 35 38 46 47 47 34]


10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [12]:
arr = np.random.randint(50, 90, 20)
print(arr)

[72 53 53 77 73 77 68 53 55 59 75 68 63 73 73 82 70 62 61 52]


11. Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.


In [13]:
arr1 = np.array([55, 44, 33, 22, 11])
arr2 = np.array([50, 40, 30, 20, 10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[105  84  63  42  21]
[5 4 3 2 1]
[2750 1760  990  440  110]
[1.1 1.1 1.1 1.1 1.1]


12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [14]:
arr = np.random.randint(10, 21, 12)
print(arr.reshape(3, 4))

[[17 14 14 20]
 [13 16 15 15]
 [14 15 10 14]]


13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [15]:
arr = np.zeros(9)
arr[0] = 1
arr[4] = 1
arr[8] = 1
print(arr.reshape(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. Write a NumPy program to find the number of rows and columns in a given     matrix. 


In [21]:
arr = np.array([[11, 22, 33], [10, 20, 30], [1, 2, 3]])
print(arr.shape)

(3, 3)


15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [17]:
arr = np.zeros(25)
arr = arr.reshape(5, 5)
arr[0, 0] = 1
arr[1,1] = 2
arr[2, 2] = 3
arr[3, 3] = 4
arr[4, 4] = 5
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [18]:
arr = np.random.random(27)
arr = arr.reshape(3, 3, 3)
print(arr)

[[[0.76819743 0.21225233 0.85183284]
  [0.02231622 0.37572518 0.91674354]
  [0.37219613 0.59173992 0.39124461]]

 [[0.55358542 0.18021464 0.06038512]
  [0.61555937 0.80689002 0.45912681]
  [0.57315024 0.97332582 0.78296628]]

 [[0.41697918 0.94679586 0.72336028]
  [0.74958933 0.12302383 0.55773564]
  [0.33631457 0.2535275  0.94639874]]]


17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [19]:
arr = np.random.random(24)
arr = arr.reshape(4, 2, 3)
print(arr)

[[[0.76799406 0.96833403 0.75240782]
  [0.44234625 0.14890972 0.35411325]]

 [[0.52679532 0.08594719 0.47855553]
  [0.72050227 0.65758482 0.52361561]]

 [[0.67118591 0.56852405 0.40658887]
  [0.07099599 0.48599064 0.31610737]]

 [[0.17985381 0.16788738 0.08802104]
  [0.03120193 0.28057093 0.14226375]]]


18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [23]:
l1 = [10, 20, 30 ,40, 50]
arr = np.array(l1)
print(arr)

[10 20 30 40 50]


19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [25]:
arr = np.random.randint(2, 10, 9)
arr = arr.reshape(3, 3)
print(arr)

[[8 9 4]
 [8 5 2]
 [2 6 7]]


20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [62]:
arr = np.arange(12, 39)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


21. Write a NumPy program to reverse an array (the first element becomes the last).

In [33]:
arr = np.array([11, 44, 77, 88, 55, 22])
print(f"Array before reverse: {arr}")
arr = arr[: : -1]
print(f"Array after reverse: {arr}")


Array before reverse: [11 44 77 88 55 22]
Array after reverse: [22 55 88 77 44 11]


22. Write a NumPy program to convert an data type into to a floating type.

In [55]:
l1 = [10, 20, 30, 40, 50]
# l1 = l1, dtype = float
print(l1)
print(f"Type of l1 = {type(l1)}")
l1 = np.array(l1, dtype = np.float32)
print(f"Type of l1 = {type(l1)}")
print(f"Dtype of l1= {l1.dtype}")

[10, 20, 30, 40, 50]
Type of l1 = <class 'list'>
Type of l1 = <class 'numpy.ndarray'>
Dtype of l1= float32


23. Write a NumPy program to convert a list array.

In [58]:
l1 = [11, 55, 99, 77, 66]
print(l1)
print(f"Type of l1= {type(l1)}")
arr = np.array(l1, dtype = np.float32) #Can't change datatypes of floats
print(arr)
print(f"Type = {type(arr)}")
print(f"DType = {arr.dtype}")

[11, 55, 99, 77, 66]
Type of l1= <class 'list'>
[11. 55. 99. 77. 66.]
Type = <class 'numpy.ndarray'>
DType = float32


24. Write a NumPy program to get the element-wise remainder of an array of division.

In [60]:
arr1 = np.array([11, 22, 33, 44, 55])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1%arr2)

[1 2 3 4 5]


25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [63]:
arr1 = np.arange(20, 50)
print(arr1%3)

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
